id: A8946303C
base_file: fFB6C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:34:40.845158
  last_modified_at: 2022-05-30 18:34:40.845164
